# Generated by Django 3.1.7 on 2021-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_books_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_Img',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
    ]
