# Generated by Django 3.1.7 on 2021-04-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210405_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Students',
        ),
    ]
